employer/urls.py
__author__ = 'jinguangzhou'
from django.conf.urls import url, include

from .views import EmployerCreateView, EmployerDetailView, jobs, dashboard, EmployerUpdateView

urlpatterns = [
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^registration/', EmployerCreateView.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/$', EmployerDetailView.as_view(), name='detail'),
    url(r'^jobs/$', jobs, name='jobs'),
    url(r'^dashboard', dashboard, name='dashboard'),
    url(r'^(?P<pk>[0-9]+)/update/$', EmployerUpdateView.as_view(), name='update'),
]

employer_jobpost/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^employers/', include('employer.urls', namespace='employer')),
    url(r'^jobs/', include('jobpost.urls', namespace='jobs')),
    url(r'^candidates/', include('candidate.urls', namespace='candidate')),
    url(r'^$', 'employer.views.index', name='index'),
]

jobpost/urls.py
__author__ = 'jinguangzhou'
from django.conf.urls import url

from .views import JobCreateView, JobUpdateView, AllJobList, JobDetailView

urlpatterns = [
    # ex: /jobs/
    url(r'^$', AllJobList.as_view(), name='list'),
    url(r'^(?P<pk>[0-9]+)/$', JobDetailView.as_view(), name='detail'),
    url(r'^create/$', JobCreateView.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/update/$', JobUpdateView.as_view(), name='update'),
]

employer/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.urlresolvers import reverse

from core.models import BaseUser


# http://www.lasolution.be/blog/creating-custom-user-model-django-16-part-2.html

# Create your models here.
class EmployerUserManager(BaseUserManager):
    def create_user(self, email, company_name, password=None):
        if not email:
            raise ValueError('Users must have email address')

        user = self.model(email=self.normalize_email(email), company_name=company_name)
        user.set_password(password)
        user.save()
        return user


class EmployerUser(BaseUser, PermissionsMixin):
    company_name = models.CharField(max_length=200)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False, blank=True)

    objects = EmployerUserManager()

    # USERNAME_FIELD = 'email'

    def __str__(self):
        return self.company_name + self.email

    def get_absolute_url(self):
        return reverse('employer:detail', kwargs={'pk': self.pk})

employer/forms.py
__author__ = 'jinguangzhou'
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, ReadOnlyPasswordHashField
from django import forms

from .models import EmployerUser


class EmployerUserCreationForm(UserCreationForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)
    email = forms.EmailField(label='Email')
    company_name = forms.CharField(label='Company Name')

    class Meta:
        model = EmployerUser
        fields = ('email', 'company_name', 'password1', 'password2')

    def clean(self):
        cleaned_data = super(EmployerUserCreationForm, self).clean()
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError("Passwords don't match. Please enter both fields again.")
        return cleaned_data

    def save(self, commit=True):
        user = super(EmployerUserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user


class EmployerUserChangeForm(UserChangeForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = EmployerUser
        fields = ('email', 'company_name', 'is_active', 'last_login')

employer/views.py
from django.shortcuts import render
from django.contrib import messages
from django.views.generic import CreateView, UpdateView, DetailView, ListView
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required

from jobpost.models import Job, JobClick
from .models import EmployerUser
from .forms import EmployerUserCreationForm


# Create your views here.
class EmployerActionMixin(object):
    @property
    def success_msg(self):
        return NotImplemented

    def form_valid(self, form):
        messages.info(self.request, self.success_msg)
        return super(EmployerActionMixin, self).form_valid(form)


class LoginRequiredMixin(object):
    @classmethod
    def as_view(cls, **initkwargs):
        view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
        return login_required(view, login_url='/employers/login')


class EmployerCreateView(EmployerActionMixin, CreateView):
    model = EmployerUser
    # Todo: how can generate view with all fields
    # fields = ('email', 'company_name', 'password', 'is_active')
    success_msg = 'Employer Created'
    form_class = EmployerUserCreationForm
    template_name = 'employer/employer_create.html'


class EmployerUpdateView(EmployerActionMixin, LoginRequiredMixin, UpdateView):
    model = EmployerUser
    fields = ('company_name', 'email')
    success_msg = 'Employer Updated'
    # Todo: show success message in ui
    success_url = '/employers/dashboard'
    template_name = 'employer/employer_update.html'


class EmployerListView(EmployerActionMixin, ListView):
    model = EmployerUser
    template_name = 'employer/employer_list.html'


class EmployerDetailView(EmployerActionMixin, LoginRequiredMixin, DetailView):
    model = EmployerUser
    template_name = 'employer/employer_detail.html'


def jobs(request, template='employer/jobs.html'):
    employ_user = EmployerUser.objects.filter(id=request.user.id)[0]
    print employ_user.company_name
    # print employ_user.company_name
    return render(request, template, {'emp_user': employ_user})


def index(request):
    return render(request, 'employer/index.html')


@login_required(login_url='/employers/login/')
def dashboard(request, template='employer/employer_dashboard.html'):
    emp_user = get_object_or_404(EmployerUser, id=request.user.id)
    print emp_user
    jobs = Job.objects.filter(employer=emp_user)
    job_click = {}
    for job in jobs:
        click = list(JobClick.objects.filter(job=job))
        job_click[job] = click
    return render(request, template, {'emp_user': emp_user, 'job_click': job_click})

templates/employer/employer_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <li>Create a new employer</li>
    <form action="{{ get_absolute_url }}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit"/>
    </form>
</head>
<body>

</body>
</html>

templates/employer/employer_dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>This is employer dashboard</title>
    {% if emp_user %}
        <p>This is {{ emp_user.company_name }} dashboard.</p>
        {% if job_click %}
            {% for job, clicks in job_click.items %}
                <p><a href="{% url 'jobs:detail' job.pk %}">{{ job.title }} has been clicked {{ job.count }}</a></p>
                {% for click in clicks %}
                    {% if click.candidate.first_name %}
                        <p>Clicked by {{ click.candidate.first_name }}</p>
                    {% else %}
                        <p>Clicked by anonymaous user.</p>
                    {% endif %}
                {% endfor %}
            {% endfor %}
        {% else %}
            <p>There is no job for {{ emp_user.company_name }}.</p>
        {% endif %}
    {% else %}
        There is no employer.
    {% endif %}
    <p><a href="{% url 'employer:update' emp_user.pk %}">Update your profile</a></p>

    <p><a href="{% url 'jobs:create' %}">Create a new job</a></p>

    <p><a href="{% url 'employer:logout' %}">Logout</a></p>
</head>
<body>

</body>
</html>

templates/employer/employer_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>
{% if employeruser %}
    <ul>
        <li><a href="{{ employeruser.get_absolute_url }}update">Update</a></li>
        <li>{{ employeruser.company_name }}</li>
        <li>{{ employeruser.email }}</li>
    </ul>
{% else %}
    <p>No Employer User.</p>
{% endif %}

templates/employer/employer_update.html
{% block content %}
    <form action="{{ get_absloute_path }}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="submit"/>
    </form>
{% endblock content %}

templates/employer/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>This is index page</title>

    <h1>This is index page</h1>
    <a href="{% url 'employer:login' %}">Employer Login</a>
    <a href="{% url 'candidate:login' %}">Candidate Login</a>
</head>
<body>

</body>
</html>