employer/urls.py
__author__ = 'jinguangzhou'
from django.conf.urls import url, include

from .views import EmployerCreateView, EmployerDetailView, jobs, dashboard, EmployerUpdateView

urlpatterns = [
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^registration/', EmployerCreateView.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/$', EmployerDetailView.as_view(), name='detail'),
    url(r'^jobs/$', jobs, name='jobs'),
    url(r'^dashboard', dashboard, name='dashboard'),
    url(r'^(?P<pk>[0-9]+)/update/$', EmployerUpdateView.as_view(), name='update'),
]

employer_jobpost/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^employers/', include('employer.urls', namespace='employer')),
    url(r'^jobs/', include('jobpost.urls', namespace='jobs')),
    url(r'^candidates/', include('candidate.urls', namespace='candidate')),
    url(r'^$', 'employer.views.index', name='index'),
]

jobpost/urls.py
__author__ = 'jinguangzhou'
from django.conf.urls import url

from .views import JobCreateView, JobUpdateView, AllJobList, JobDetailView

urlpatterns = [
    # ex: /jobs/
    url(r'^$', AllJobList.as_view(), name='list'),
    url(r'^(?P<pk>[0-9]+)/$', JobDetailView.as_view(), name='detail'),
    url(r'^create/$', JobCreateView.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/update/$', JobUpdateView.as_view(), name='update'),
]

employer/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.urlresolvers import reverse

from core.models import BaseUser


# http://www.lasolution.be/blog/creating-custom-user-model-django-16-part-2.html

# Create your models here.
class EmployerUserManager(BaseUserManager):
    def create_user(self, email, company_name, password=None):
        if not email:
            raise ValueError('Users must have email address')

        user = self.model(email=self.normalize_email(email), company_name=company_name)
        user.set_password(password)
        user.save()
        return user


class EmployerUser(BaseUser, PermissionsMixin):
    company_name = models.CharField(max_length=200)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False, blank=True)

    objects = EmployerUserManager()

    # USERNAME_FIELD = 'email'

    def __str__(self):
        return self.company_name + self.email

    def get_absolute_url(self):
        return reverse('employer:detail', kwargs={'pk': self.pk})

jobpost/models.py
from django.db import models
from django.core.urlresolvers import reverse
from model_utils.models import TimeStampedModel

from candidate.models import CandidateUser
from employer.models import EmployerUser


# Create your models here.
class Address(TimeStampedModel):
    address_line1 = models.CharField(max_length=200, blank=False)
    address_line2 = models.CharField(max_length=200)
    address_line3 = models.CharField(max_length=200)
    city = models.CharField(max_length=200, blank=False)
    country_state = models.CharField(max_length=200, blank=False)
    zipcode = models.CharField(max_length=200, blank=False)
    country_id = models.CharField(max_length=200, blank=False)
    other_address_details = models.CharField(max_length=400, blank=True)

    def __unicode__(self):
        return '{0}'.format(self.address_line1)


class AddressType(TimeStampedModel):
    """
    This is model for address type, home, work, delivery
    """
    code = models.CharField(max_length=200, null=False, blank=False, primary_key=True)
    description = models.CharField(max_length=200)

    def __unicode__(self):
        return '{0}'.format(self.code)


class Plan(models.Model):
    """
    This is service plan model
    """
    name = models.CharField(max_length=200, blank=False, primary_key=True)
    fee = models.FloatField(blank=False, default=0.0)
    description = models.TextField()

    def __unicode__(self):
        return '{0}'.format(self.name)


class CreditCard(TimeStampedModel):
    """
    This is model to save credit card information
    """
    employer = models.ForeignKey(EmployerUser, on_delete=models.CASCADE)
    type = models.CharField(max_length=200)
    holder_name = models.CharField(max_length=200)
    number = models.CharField(max_length=16)
    security_code = models.CharField(max_length=3)
    expiration_date_month = models.CharField(max_length=2)
    expiration_date_year = models.CharField(max_length=4)
    is_default = models.BooleanField(default=False)

    def __unicode__(self):
        return '{0} {1}'.format(self.type, self.holder_name)


class EmployerAddress(TimeStampedModel):
    address = models.ForeignKey(Address, on_delete=models.CASCADE)
    address_type = models.ForeignKey(AddressType, on_delete=models.CASCADE)
    employer = models.ForeignKey(EmployerUser, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('address', 'address_type', 'employer'),)

    def __unicode__(self):
        return '{0} {1} {2}'.format(self.address.address_line1, self.address_type.code, self.employer.employer_name)


class CandidateAddress(TimeStampedModel):
    address = models.ForeignKey(Address, on_delete=models.CASCADE)
    address_type = models.ForeignKey(AddressType, on_delete=models.CASCADE)
    candidate = models.ForeignKey(CandidateUser, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('address', 'address_type', 'candidate'),)

    def __unicode__(self):
        return '{0} {1} {2}'.format(self.address.address_line1, self.address_type.code, self.candidate.first_name)


class Job(models.Model):
    title = models.CharField(max_length=200, blank=False)
    description = models.TextField()
    link = models.URLField()
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    employer = models.ForeignKey(EmployerUser, on_delete=models.CASCADE)
    count = models.IntegerField(default=0, blank=True)

    def __unicode__(self):
        return '{0} {1}'.format(self.title, self.employer.company_name)

    def get_absolute_url(self):
        return reverse('jobs:all_job_detail', kwargs={'pk': self.pk})


class JobClick(TimeStampedModel):
    """
     This is model to track job click information
    """
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    # anonymous user click without candidate id
    candidate = models.ForeignKey(CandidateUser, on_delete=models.CASCADE, blank=True, null=True)

    def __unicode__(self):
        return '{0} {1}'.format(self.job.title, self.job.employer.company_name)


class Payment(TimeStampedModel):
    """
    This is model to track payment information
    """
    employer = models.ForeignKey(EmployerUser, on_delete=models.PROTECT)
    card = models.ForeignKey(CreditCard, on_delete=models.PROTECT)
    description = models.TextField()
    plan = models.ForeignKey(Plan, on_delete=models.PROTECT)

    def __unicode__(self):
        return '{0} {1}'.format(self.employer.employer_name, self.description)

employer/forms.py
__author__ = 'jinguangzhou'
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, ReadOnlyPasswordHashField
from django import forms

from .models import EmployerUser


class EmployerUserCreationForm(UserCreationForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)
    email = forms.EmailField(label='Email')
    company_name = forms.CharField(label='Company Name')

    class Meta:
        model = EmployerUser
        fields = ('email', 'company_name', 'password1', 'password2')

    def clean(self):
        cleaned_data = super(EmployerUserCreationForm, self).clean()
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError("Passwords don't match. Please enter both fields again.")
        return cleaned_data

    def save(self, commit=True):
        user = super(EmployerUserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user


class EmployerUserChangeForm(UserChangeForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = EmployerUser
        fields = ('email', 'company_name', 'is_active', 'last_login')

jobpost/forms.py
__author__ = 'jinguangzhou'
from django.forms import ModelForm, forms

from .models import Job


class JobForm(ModelForm):
    class Meta:
        model = Job
        fields = ('title', 'description', 'link', 'city', 'state', 'country', 'employer')

    def clean(self):
        cleaned_data = super(JobForm, self).clean()
        title = cleaned_data.get('title')

        if Job.objects.filter(title=title):
            raise forms.ValidationError(u"Title is in the database.")
        return cleaned_data

employer/views.py
from django.shortcuts import render
from django.contrib import messages
from django.views.generic import CreateView, UpdateView, DetailView, ListView
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required

from jobpost.models import Job, JobClick
from .models import EmployerUser
from .forms import EmployerUserCreationForm


# Create your views here.
class EmployerActionMixin(object):
    @property
    def success_msg(self):
        return NotImplemented

    def form_valid(self, form):
        messages.info(self.request, self.success_msg)
        return super(EmployerActionMixin, self).form_valid(form)


class LoginRequiredMixin(object):
    @classmethod
    def as_view(cls, **initkwargs):
        view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
        return login_required(view, login_url='/employers/login')


class EmployerCreateView(EmployerActionMixin, CreateView):
    model = EmployerUser
    # Todo: how can generate view with all fields
    # fields = ('email', 'company_name', 'password', 'is_active')
    success_msg = 'Employer Created'
    form_class = EmployerUserCreationForm
    template_name = 'employer/employer_create.html'


class EmployerUpdateView(EmployerActionMixin, LoginRequiredMixin, UpdateView):
    model = EmployerUser
    fields = ('company_name', 'email')
    success_msg = 'Employer Updated'
    # Todo: show success message in ui
    success_url = '/employers/dashboard'
    template_name = 'employer/employer_update.html'


class EmployerListView(EmployerActionMixin, ListView):
    model = EmployerUser
    template_name = 'employer/employer_list.html'


class EmployerDetailView(EmployerActionMixin, LoginRequiredMixin, DetailView):
    model = EmployerUser
    template_name = 'employer/employer_detail.html'


def jobs(request, template='employer/jobs.html'):
    employ_user = EmployerUser.objects.filter(id=request.user.id)[0]
    print employ_user.company_name
    # print employ_user.company_name
    return render(request, template, {'emp_user': employ_user})


def index(request):
    return render(request, 'employer/index.html')


@login_required(login_url='/employers/login/')
def dashboard(request, template='employer/employer_dashboard.html'):
    emp_user = get_object_or_404(EmployerUser, id=request.user.id)
    print emp_user
    jobs = Job.objects.filter(employer=emp_user)
    job_click = {}
    for job in jobs:
        click = list(JobClick.objects.filter(job=job))
        job_click[job] = click
    return render(request, template, {'emp_user': emp_user, 'job_click': job_click})

jobpost/views.py
from django.views.generic import CreateView, UpdateView, DetailView, ListView
from django.contrib.auth.models import AnonymousUser

from .models import Job, JobClick, CandidateUser


# Create your views here.

class JobActionMixin(object):
    @property
    def success_msg(self):
        return NotImplemented

    def get_context_data(self, **kwargs):
        """Add employer pk to the context"""
        context = super(JobActionMixin, self).get_context_data(**kwargs)
        if 'employer_pk' in self.kwargs:
            context['employer_pk'] = self.kwargs['employer_pk']
        return context

        # @classmethod
        # def as_view(cls, **initkwargs):
        #     view = super(JobActionMixin, cls).as_view(**initkwargs)
        #     return login_required(view)


class JobDetailView(JobActionMixin, DetailView):
    model = Job
    template_name = 'jobpost/job_detail.html'

    def get_object(self, queryset=None):
        """Add more logic like, #click here"""
        object = super(JobDetailView, self).get_object()
        candidate = None
        if self.request.user:
            candidate = CandidateUser.objects.filter(baseuser_ptr_id=self.request.user.id)[0]
        else:
            candidate = AnonymousUser()
        job_click = JobClick(job=object, candidate=candidate)
        job_click.save()
        object.count = object.count + 1
        object.save()
        return object


class JobCreateView(JobActionMixin, CreateView):
    model = Job
    template_name = 'jobpost/job_create.html'
    fields = ('title', 'description', 'link', 'employer')
    success_url = '/employers/dashboard'


class JobUpdateView(JobActionMixin, UpdateView):
    model = Job
    fields = ('title', 'description', 'link')
    success_msg = 'Job Updated'
    template_name = 'jobpost/job_update.html'
    success_url = '/employers/dashboard'


class AllJobList(ListView):
    model = Job
    template_name = 'jobpost/all_job_list.html'

templates/jobpost/all_job_list.html
{% if job_list %}
    <ul>
        {% for job in job_list %}
            <li><a href="{% url 'jobs:detail' job.pk %}">{{ job.title }}</a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No Jobs.</p>
{% endif %}

templates/jobpost/employer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

{% if employer_list %}
    <ul>
        {% for employer in employer_list %}
            <li><a href="/employers/{{ employer.pk }}/">{{ employer.employer_name }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No Employer.</p>
{% endif %}

templates/jobpost/employer_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>
{% if employer %}
    <ul>
        <li><a href="{{ employer.get_absolute_url }}update">Update</a></li>
        <li>{{ employer.employer_name }}</li>
        <li>{{ employer.email }}</li>
        <li>{{ employer.phone_number }}</li>
        <li>{{ employer.plan.name }}</li>
    </ul>
{% else %}
    <p>No Employer.</p>
{% endif %}
<ul>
    <li><a href="{% url "employers:job_list" employer_pk=employer.pk %}">List jobs</a></li>
</ul>
<ul>
    <li><a href="{% url "employers:job_create" employer_pk=employer.pk %}">Create a jobs</a></li>
</ul>

templates/jobpost/employer_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>
<!-- Default context variable-->
{% if employer_list %}
    <ul>
        {% for emp in employer_list %}
            <li><a href="{{ emp.get_absolute_url }}">{{ emp.employer_name }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No Employer.</p>
{% endif %}
<ul>
    <li><a href="{% url "employers:create" %}">Create a new employer</a></li>
</ul>

templates/jobpost/employer_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

{% if employer %}
    <ul>
        {{ employer.employer_name }}
    </ul>
    <ul>
        {{ employer.plan.name }}
    </ul>
{% else %}
    <p>No Employer.</p>
{% endif %}

templates/jobpost/employer_update.html
{% extends "base.html" %}
{% block content %}
    <form action="{{ get_absloute_path }}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="submit"/>
    </form>
{% endblock content %}

templates/jobpost/job_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Job create</title>

    <form action="{% url 'employers:job_create' employer_pk=employer_pk %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit"/>
    </form>
</head>
<body>

</body>
</html>

templates/jobpost/job_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>
{% if job %}
    <ul>
        <li>{{ job.title }}</li>
        <li>{{ job.link }}</li>
        {% if user.is_authenticated %}
            <p><a href="{% url 'jobs:update' job.pk %}">Update job</a></p>
        {% endif %}

    </ul>
{% else %}
    <p>No Jobs.</p>

{% endif %}

templates/jobpost/job_list.html
{% if job_list %}
    <ul>
        {% for job in job_list %}
            <li><a href="{% url 'employers:job_detail' employer_pk=employer_pk pk=job.pk %}">{{ job.title }}</a> Click
                Times {{ job.count }}
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No Jobs.</p>
{% endif %}

<li><a href="{% url "employers:job_create" employer_pk=employer_pk %}">Create a jobs</a></li>

templates/jobpost/job_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>