candidate/urls.py
__author__ = 'jinguangzhou'
from django.conf.urls import url, include

from .views import CandidateCreateView, CandidateUserDetailsView, dashboard, CandidateUserUpdateView

urlpatterns = [
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^registration', CandidateCreateView.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/$', CandidateUserDetailsView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/update/$', CandidateUserUpdateView.as_view(), name='update'),
    url(r'^dashboard', dashboard, name='dashboard'),
    # Todo: update view
]

employer_jobpost/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^employers/', include('employer.urls', namespace='employer')),
    url(r'^jobs/', include('jobpost.urls', namespace='jobs')),
    url(r'^candidates/', include('candidate.urls', namespace='candidate')),
    url(r'^$', 'employer.views.index', name='index'),
]

jobpost/urls.py
__author__ = 'jinguangzhou'
from django.conf.urls import url

from .views import JobCreateView, JobUpdateView, AllJobList, JobDetailView

urlpatterns = [
    # ex: /jobs/
    url(r'^$', AllJobList.as_view(), name='list'),
    url(r'^(?P<pk>[0-9]+)/$', JobDetailView.as_view(), name='detail'),
    url(r'^create/$', JobCreateView.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/update/$', JobUpdateView.as_view(), name='update'),
]

candidate/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager
from django.core.urlresolvers import reverse

from core.models import BaseUser


# Create your models here.
class CandidateUserManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, password=None):
        user = self.model(email=self.normalize_email(email), first_name=first_name, last_name=last_name)
        user.set_password(password)
        user.save()
        return user


class CandidateUser(BaseUser):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = CandidateUserManager()

    def get_absolute_url(self):
        return reverse('candidate:detail', kwargs={'pk': self.pk})

candidate/forms.py
__author__ = 'jinguangzhou'
from django.contrib.auth.forms import UserCreationForm
from django import forms

from .models import CandidateUser


class CandidateUserCreationUserForm(UserCreationForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password Confirmation', widget=forms.PasswordInput)
    email = forms.EmailField(label='Email')
    first_name = forms.CharField(label='First Name')
    last_name = forms.CharField(label='Last Name')

    class Meta:
        model = CandidateUser
        fields = ('email', 'first_name', 'last_name', 'password1', 'password2')

    def clean(self):
        cleaned_data = super(CandidateUserCreationUserForm, self).clean()
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError("Passwords don't match. Please enter both fields again.")
        return cleaned_data

    def save(self, commit=True):
        user = super(CandidateUserCreationUserForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

candidate/views.py
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView, DetailView
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required

from .models import CandidateUser
from .forms import CandidateUserCreationUserForm


# Create your views here.
class CandidateUserActionMixin(object):
    @property
    def success_msg(self):
        return NotImplemented

    @classmethod
    def as_view(cls, **initkwargs):
        view = super(CandidateUserActionMixin, cls).as_view(**initkwargs)
        return login_required(view, login_url='/candidates/login')
        # todo: issues with registration page, it directs to /account


class LoginRequiredMixin(object):
    @classmethod
    def as_view(cls, **initkwargs):
        view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
        return login_required(view, login_url='/candidates/login')


class CandidateCreateView(CandidateUserActionMixin, CreateView):
    model = CandidateUser
    success_msg = 'Candidate User created'
    form_class = CandidateUserCreationUserForm
    template_name = 'candidate/registration.html'


class CandidateUserDetailsView(CandidateUserActionMixin, LoginRequiredMixin, DetailView):
    model = CandidateUser
    template_name = 'candidate/detail.html'


class CandidateUserUpdateView(CandidateUserActionMixin, LoginRequiredMixin, UpdateView):
    model = CandidateUser
    template_name = 'candidate/candidate_update.html'
    fields = ('first_name', 'last_name')
    success_url = '/candidates/dashboard'
    success_msg = 'Candidate updated.'


@login_required(login_url='/candidates/login/')
def dashboard(request, template='candidate/candidate_dashboard.html'):
    can_user = get_object_or_404(CandidateUser, id=request.user.id)
    return render(request, template, {'can_user': can_user})

templates/candidate/candidate_dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>This is candidate dashboard</title>
    {% if can_user %}
        <p>Welcome to {{ can_user.first_name }} dashboard.</p>
    {% else %}
        There is no candidate.
    {% endif %}
    <a href="{% url 'candidate:update' can_user.pk %}">Update candidate profile</a>

    <p><a href="{% url 'candidate:logout' %}">Log out</a></p>

    <p><a href="{% url 'jobs:list' %}">Go to job list</a></p>
</head>
<body>

</body>
</html>

templates/candidate/candidate_update.html
{% block content %}
    <form action="{{ get_absloute_path }}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="submit"/>
    </form>
{% endblock content %}

templates/candidate/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>
{% if candidateuser %}
    <ul>
        <li><a href="{{ candidateuser.get_absolute_url }}update">Update</a></li>
        <li>{{ candidateuser.email }}</li>
        <li>{{ candidateuser.first_name }}</li>
        <li>{{ candidateuser.last_name }}</li>
    </ul>
{% else %}
    <p>No Candidate User.</p>
{% endif %}

templates/candidate/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <li>Create a new candidate</li>
    <form action="{{ get_absolute_url }}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit"/>
    </form>
</head>
<body>

</body>
</html>